version: "3.8"

services:
  app:
    container_name: fastapiapp
    build: ./
    depends_on:
      mysql_db:
        condition: service_healthy
    command: bash -c "uv run main.py && uv run alembic revision --autogenerate"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    restart: always
    env_file:
      - docker.env

  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - ./dbdata:/var/lib/mysql/

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 3s